server:
  port: 9091

spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/common-code?characterEncoding=utf-8&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  redis:
    host: 192.168.0.104
    port: 6379
# sql监控
decorator:
  datasource:
    p6spy:
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
      # 自定义日志类
      logging: custom
      custom-appender-class:  com.arvin.it.common.StdoutLogger