server.port=9091
spring.main.allow-bean-definition-overriding=true

spring.shardingsphere.def
spring.shardingsphere.props.sql-show=true
#------------------------- 数据源配置
# 指定对应的库
spring.shardingsphere.datasource.names=m0,m1
# 数据库m0的数据源配置
spring.shardingsphere.datasource.m0.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.m0.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.m0.url=jdbc:mysql://localhost:3306/common-code?characterEncoding=utf-8&serverTimezone=UTC
spring.shardingsphere.datasource.m0.username=root
spring.shardingsphere.datasource.m0.password=root
# 数据库m1的数据源配置
spring.shardingsphere.datasource.m1.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.m1.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.m1.url=jdbc:mysql://localhost:3306/common-code?characterEncoding=utf-8&serverTimezone=UTC
spring.shardingsphere.datasource.m1.username=root
spring.shardingsphere.datasource.m1.password=root

# 雪花算法，生成Long类型主键
spring.shardingsphere.rules.sharding.key-generators.alg_snowflake.type=SNOWFLAKE
spring.shardingsphere.rules.sharding.key-generators.alg_snowflake.props.worker-id=1
#------------------------- 分布式序列算法配置
# 指定分布式主键生成策略
spring.shardingsphere.rules.sharding.tables.t_log.key-generate-strategy.column=id
spring.shardingsphere.rules.sharding.tables.t_log.key-generate-strategy.key-generator-name=alg_snowflake

#------------------------- 配置实际分片节点 course：逻辑表
spring.shardingsphere.rules.sharding.tables.t_log.actual-data-nodes=m$->{0..1}.t_log_$->{2025..2026}$->{1..12}$->{1..31}_$->{0..5}
# 分库以及分库算法
spring.shardingsphere.rules.sharding.tables.t_log.database-strategy.standard.sharding-column=id
spring.shardingsphere.rules.sharding.tables.t_log.database-strategy.standard.sharding-algorithm-name=course_db_alg
spring.shardingsphere.rules.sharding.sharding-algorithms.course_db_alg.type=MOD
spring.shardingsphere.rules.sharding.sharding-algorithms.course_db_alg.props.sharding-count=2
# 分表以及分表算法
spring.shardingsphere.rules.sharding.tables.t_log.table-strategy.complex.sharding-columns=create_time,trace_id
spring.shardingsphere.rules.sharding.tables.t_log.table-strategy.complex.sharding-algorithm-name=course_tbl_alg
spring.shardingsphere.rules.sharding.sharding-algorithms.course_tbl_alg.type=CLASS_BASED
spring.shardingsphere.rules.sharding.sharding-algorithms.course_tbl_alg.props.strategy=COMPLEX
spring.shardingsphere.rules.sharding.sharding-algorithms.course_tbl_alg.props.algorithmClassName=com.arvin.it.utils.TimeTraceComplexAlgorithm
